<?php
/**
 * Created by PhpStorm.
 * User: Boxedsolutions
 * Date: 2016-12-07
 * Time: 14:35
 */
?>
<?php $_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>
<div class="cart <?php echo $_priceDisplay; ?>">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
        <?php if(!$this->hasError()): ?>
            <ul class="checkout-types top">
                <?php foreach ($this->getMethods('top_methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                        <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div id="shopping-cart-table" class="cart-table data-table table">

            <div class="thead">
            <div class="tr">
                <div class="th"><span class="nobr"><?php echo $this->__('Product') ?></span></div>

                <div class="th">&nbsp;</div>
                <div class="th  a-center cart-price-head">
                    <!--                            <div class="cart-price-placeholder">-->
                    <span class="nobr"><?php echo $this->__('Price') ?></span>
                    <!--                            </div>-->
                </div>
                <div class="th a-center">
                    <?php echo $this->__('Qty') ?>

                    <?php /*if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span>
                        <?php endif*/ ?>

                </div>
                <div class="th a-center cart-total-head" >
                    <!--                            <div class="cart-total-placeholder">-->
                    <?php echo Mage::helper('billmatecommon')->__('Rowtotal') ?>
                    <!--                            </div>-->
                </div>

                <div class="th a-center">&nbsp;</div>

            </div>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <div class="tr">
                    <div class="th a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></div>
                    <div  class="th a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></div>
                    <div class="th a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></div>
                    <div class="th a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></div>
                </div>
            <?php endif; ?>
            </div>

            <div class="tbody">
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
            </div>
        </div>
        <script type="text/javascript">decorateTable('shopping-cart-table')</script>
    </form>

    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
    <div class="billmate-cart-forms">
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('checkout_cart_widget') ?>
        <?php echo $this->getChildHtml('coupon') ?>
        <?php echo $this->getChildHtml('checkout.cart.extra') ?>
        <div id="shipping-container">
            <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>

        </div>
    </div>
    <div class="billmate-cart-totals-wrapper">
        <div class="cart-totals">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
                <ul class="checkout-types bottom">
                    <?php foreach ($this->getMethods('methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                            <li class="method-<?php echo preg_replace("/[^_a-zA-Z0-9-]/", '-', $method); ?>"><?php echo $methodHtml; ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('crosssell') ?>
</div>
