<?php
/**
 * Created by PhpStorm.
 * User: Boxedsolutions
 * Date: 2016-09-26
 * Time: 11:59
 */

$checkout = $this->getCheckoutUrl();
?>
<?php echo $this->getChildHtml('checkout.cart'); ?>
<script>
    var UPDATE_ADDRESS_URL = "<?php echo Mage::getUrl('billmatecommon/billmatecheckout/updateaddress',array('_secure' => true)); ?>";
    var UPDATE_PAYMENT_METHOD_URL = "<?php echo Mage::getUrl('billmatecommon/billmatecheckout/updatepaymentmethod',array('_secure' => true)); ?>";
    var UPDATE_SHIPPING_METHOD_URL = "<?php echo Mage::getUrl('billmatecommon/billmatecheckout/updateshippingmethod',array('_secure' => true)); ?>";
    var CREATE_ORDER_URL = "<?php echo Mage::getUrl('billmatecommon/billmatecheckout/createorder',array('_secure' => true)); ?>";
    var UPDATE_TOTALS_URL = "<?php echo Mage::getUrl('billmatecommon/billmatecheckout/updatetotals',array('_secure' => true)); ?>";
    var UPDATE_DISCOUNT_URL = "<?php echo Mage::getUrl('billmatecommon/billmatecheckout/setdiscount',array('_secure' => true)); ?>";
    var CHECKOUT_URL = "<?php echo Mage::getUrl('billmatecommon/billmatecheckout/index',array('_secure' => true)); ?>"
</script>
<div id="checkout-loader">
    <div class="img-loader"></div>
</div>
<?php if(count(Mage::getSingleton('checkout/cart')->getQuote()->getAllVisibleItems()) > 0 ){ ?>

<div id="checkoutdiv">
    <iframe id="checkout" src="<?php echo $checkout; ?>" style="width: 100%; min-height: 800px; border:none;" sandbox="allow-same-origin allow-scripts allow-modals allow-popups allow-forms allow-top-navigation"></iframe>
    <div class="billmateoverlay"></div>
    <div class="billmateloading"></div>
</div>
<?php } ?>

