<?php
/**
 * Created by PhpStorm.
 * User: Boxedsolutions
 * Date: 2016-12-07
 * Time: 13:12
 */ ?>
<div class="billmate-shipping">
<?php
if (($_shippingRateGroups = $this->getEstimateRates())): ?>
    <?php echo Mage::helper('checkout')->__('Shipping Method'); ?>
    <form id="co-shipping-method-form" action="<?php echo $this->getUpdateFormActionUrl() ?>">
        <dl class="sp-methods">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
                <dd>
                    <ul>
                        <?php foreach ($_rates as $_rate): ?>
                            <li<?php if ($_rate->getErrorMessage()) echo ' class="error-msg"';?>>
                                <?php if ($_rate->getErrorMessage()): ?>
                                    <?php echo $this->escapeHtml($_rate->getErrorMessage()) ?>
                                <?php else: ?>
                                    <input name="estimate_method" type="radio" value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
                                    <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                        <?php echo $_excl; ?>
                                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                        <?php endif; ?>
                                    </label>
                                <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </dd>
            <?php endforeach; ?>
        </dl>
    </form>
<?php endif; ?>
<script type="text/javascript">
    //<![CDATA[
    var coShippingMethodForm = new VarienForm('shipping-zip-form');
    var countriesWithOptionalZip = <?php echo $this->helper('directory')->getCountriesWithOptionalZip(true) ?>;

    coShippingMethodForm.submit = function () {
        /*var country = $F('country');
        var optionalZip = false;

        for (i=0; i < countriesWithOptionalZip.length; i++) {
            if (countriesWithOptionalZip[i] == country) {
                optionalZip = true;
            }
        }
        if (optionalZip) {
            $('postcode').removeClassName('required-entry');
        }
        else {
            $('postcode').addClassName('required-entry');
        }*/
        return VarienForm.prototype.submit.bind(coShippingMethodForm)();
    };
    
    var billmateCheckoutShippingTimer;
    var selectedShippingMethod = null;
    if($$('[name="estimate_method"]:checked').length == 0){
        jQuery('[name="estimate_method"]').last().click();
    } else {
        selectedShippingMethod = $$('[name="estimate_method"]:checked')[0].value;
    }
    $$('[name="estimate_method"].radio').each(function(el){
        el.observe('click',function(e){

            clearTimeout(billmateCheckoutShippingTimer);
            billmateCheckoutShippingTimer = setTimeout(function() {
                if($$('[name="estimate_method"]:checked')[0].value != selectedShippingMethod) {
                    selectedShippingMethod = $$('[name="estimate_method"]:checked')[0].value;
                    updateShippingMethod($$('[name="estimate_method"]:checked')[0].value);
                }
            }, 500);
        });

    });

    function updateShippingMethod(method) {
        new Ajax.Request('<?php echo Mage::getUrl('billmatecommon/billmatecheckout/updateshippingmethod', array('_secure' => true)) ?>',{
            parameters: {estimate_method: method},
            method: 'post',
            onSuccess: function(transport){
                var result = transport.responseText.evalJSON();
                if(result.success){

                }
            }
        });
    }

    //]]>
</script>
</div>
