<li class="fields">
    <div class="billmate-getaddress">
        <div class="pno">
        <label for="pno"><?php echo $this->__('Social Security Number / Corporate Registration Number'); ?></label>
            <div class="input-box">
                <input type="text"
                       name="billmate_pno"
                       id="person_number"
                       class="input-text"
                       value="<?php echo $this->getParentBlock()->getPno() ?>"/>
            </div>
        </div>
        <div style="float:left; padding-top:18px;padding-left:5px;" class="fetch">
            <div class="input-box">
                <button class="button" id="billmategetaddress">
                    <span><?php echo $this->__('Get Address'); ?></span>
                </button>
            </div>
        </div>
    </div>
</li>
<div style="clear:both;"></div>