<?php $gateway = Mage::getSingleton('partpayment/gateway');

$fieldname = array(	'street][','city','postcode');
$groupname = array('billing','shipping');
$address   = array_combine(
				$fieldname,
				array($gateway->street, $gateway->city, $gateway->postcode)
			);
if(strlen($gateway->getFirstname())>0){
	$fieldname[] = 'firstname';
	$address['firstname'] = $gateway->getFirstname();
}
if(strlen($gateway->getLastname())>0){
	$fieldname[] = 'lastname';
	$address['lastname'] = $gateway->getLastname();
}
if(strlen($gateway->getCompany())>0){
	$fieldname[] = 'company';
	$address['company'] = $gateway->getCompany();
}

if($this->isMatched()):
	echo 'if(typeof streamcheckout != "undefined"){'."\n";
	if(Mage::getStoreConfig('firecheckout/general/enabled') && Mage::getSingleton('customer/session')->isLoggedIn()){
		echo 'billing.newAddress(true)'."\n";

	}
	foreach( $groupname as $group ){
		foreach($fieldname as $row){
			echo 'if($$(\'input[name="'.$group.'['.$row.']"]\').size() > 0 ){ $$(\'input[name="'.$group.'['.$row.']"]\')[0].value="'.$address[$row].'";}',"\n";

		}
		if(Mage::getSingleton('customer/session')->isLoggedIn())
			echo 'if($$(\'input[name="'.$group.'[telephone]"\').size()>0){ $$(\'input[name="'.$group.'[telephone]\')[0].value="'.$gateway->telephone.'";}',"\n";

		echo 'if($$(\'[name="'.$group.'[country_id]"]\').size()>0){ $$(\'[name="'.$group.'[country_id]"]\')[0].value="'.$gateway->country.'";}'."\n";
	}

	echo 'closefunc();modalWin.HideModalPopUp();paymentSave();',"\n";
	echo '}'."\n";

	echo 'if((typeof checkout != "undefined" && typeof checkout.form != "undefined" ) || typeof checkoutForm != "undefined" || typeof OneStepCheckoutLoginPopup != "undefined"){',"\n";
	if(Mage::getStoreConfig('firecheckout/general/enabled') && Mage::getSingleton('customer/session')->isLoggedIn()){
		echo 'billing.newAddress(true)'."\n";

	}
	foreach( $groupname as $group ){
		foreach($fieldname as $row){
			echo 'if($$(\'input[name="'.$group.'['.$row.']"]\').size() > 0 ){ $$(\'input[name="'.$group.'['.$row.']"]\')[0].value="'.$address[$row].'";}',"\n";
		}
		if(Mage::getSingleton('customer/session')->isLoggedIn())
			echo 'if($$(\'input[name="'.$group.'[telephone]"\').size()>0){ $$(\'input[name="'.$group.'[telephone]\')[0].value="'.$gateway->telephone.'";}',"\n";
		echo 'if($$(\'[name="'.$group.'[country_id]"]\').size()>0){ selectDropDown($$(\'[name="'.$group.'[country_id]"]\')[0],\''.$gateway->country.'\');}',"\n";
	}
	echo 'closefunc();modalWin.HideModalPopUp();',"\n";
	echo '}
paymentSave();';
 ?>

<?php else: ?>
	<?php
		$name = ($gateway->company != '') ? $gateway->company : $gateway->firstname.' '.$gateway->lastname;
		$country = $gateway->country == 'se' ? '':$gateway->country_name;
		$yestext = $this->__('Yes, make purchase with this address.');
		$notext = $this->__('No, I want to specify another person / company or change payment method.');
		$explanation = $this->__('Pay with invoice can only be made with a registered adress. Would you like to make the purchase with the following registered address:');
	?>
	<?php
	if(Mage::getStoreConfig('firecheckout/general/enabled'))
		echo json_encode(array('update_section' => array('name' => 'sagepay-iframe', 'html' => "<script>html='<span style=\"line - height: 1.4em;\">$name<br>$gateway->street<br>$gateway->postcode<br/>$gateway->city<br/>$country</span><div style=\"margin - top:1em\"><input type=\"button\" id=\"updateAddressYes\" onclick=\"updateAddress()\" value=\"$yestext\" class=\"billmate_button\"/></div><div><a onclick=\"modalWin . HideModalPopUp();\" class=\"linktag\" >$notext</a></div>';\nShowMessage(html,'$explanation');</script>")));
	else
		echo json_encode(array('update_section' => array('name' => 'billmate', 'html' => "<script>html='<span style=\"line - height: 1.4em;\">$name<br>$gateway->street<br>$gateway->postcode<br/>$gateway->city<br/>$country</span><div style=\"margin - top:1em\"><input type=\"button\" id=\"updateAddressYes\" onclick=\"updateAddress()\" value=\"$yestext\" class=\"billmate_button\"/></div><div><a onclick=\"modalWin . HideModalPopUp();\" class=\"linktag\" >$notext</a></div>';\nShowMessage(html,'$explanation');</script>")));


endif;
