<?php $_code=$this->getMethodCode();
$lang = explode('_',Mage::app()->getLocale()->getLocaleCode());
$customerData['email'] = '';
if($customer = Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customerData = Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getId())->getData();
}else{
$customerData['email'] = Mage::getSingleton('checkout/session')
	->getQuote()
	->getBillingAddress()
	->email;
}
if (Mage::getStoreConfig('firecheckout/general/enabled') && Mage::getStoreConfig('billmate/settings/getaddress') && !Mage::getSingleton('customer/session')->isLoggedIn()){
	$padding = 'margin-right: 10px;';
    $visuality = 'display:none';
} else {
	$padding = '';
    $visuality = 'display:block';
}
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>/billmate/images/<?php echo $lang[0] == 'sv' ? $lang[0] : 'en'; ?>/partpayment.png" />
    </li>
    <li style="<?php echo $visuality; ?>">
        <label for="<?php echo $_code ?>_pno" class="required"><em>*</em><?php echo $this->__('Social Security Number / Corporate Registration Number') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Personal Number') ?>" class="input-text required-entry" id="<?php echo $_code ?>_pno" name="payment[<?php echo $_code ?>_pno]" value="" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_phone" class="required"><em>*</em><?php echo $this->__('Payment Options') ?></label>
        <div class="input-box">
			<select name="pclass" id="pclass">
			<?php
				$terms = $this->termsx();
				$currency = Mage::app()->getStore()->getCurrentCurrencyCode(); 
				foreach( $terms as $term ){
					$label = $term['description']. ' '.round( Mage::helper('core')->currency( $term['monthly_cost'], false, true),2).' '.$currency.' / '. Mage::helper('partpayment')->__('month');
					echo '<option value="'.$term['pclass_id'].'">'.$label.'</option>';
				}
			?>
			</select>
        </div>
    </li>
    <li style="display:inline-flex">
		<input type="checkbox" onchange="checkAddress(this)" checked="checked" id="<?php echo $_code ?>_phone" name="payment[<?php echo $_code;?>_phone]" title="<?php echo $this->__('Phone Number') ?>" class="required-entry" value="on" style="float:left;margin:3px; <?php echo $padding; ?>" />
        <label class="required" style="font-weight:normal"><em>*</em><?php echo $this->__('My email%1$s is accurate and can be used for invoicing. I also confirm the',($customerData['email'] != '') ? ', <b>'.$customerData['email'].'</b>,' :'') ?> <a id="terms-delbetalning" style="float:none!important;   margin-left: 0px!important;"><?php echo $this->__('terms & conditions'); ?></a>, <a href="https://www.billmate.se/integritetspolicy/" target="_blank" style="float:none!important; margin-left: 0px!important;"><?php echo $this->__('Privacy Policy'); ?></a> <?php echo $this->__('and accept the liability.'); ?> </label>
    </li>
    <?php echo $this->getChildHtml() ?>
	<input type="hidden" name="<?php echo $_code ?>_index" value="<?php echo Mage::getUrl('partpayment/index',array('_secure' => true)) ?>"/>
	<input type="hidden" name="<?php echo $_code ?>_update" value="<?php echo Mage::getUrl('partpayment/index/updateAddress',array('_secure' => true)) ?>"/>
</ul>
<script type="text/javascript">
var billmateindexurl = "<?php echo Mage::getUrl('billmateinvoice/index',array('_secure' => true)) ?>";
var billmatesaveurl  = '<?php echo Mage::getUrl('billmateinvoice/index/updateAddress',array('_secure' => true));?>';
var skinurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>';
var PARTPAYMENT_EID = '<?php echo Mage::getStoreConfig('payment/billmatepartpayment/eid'); ?>';
var PNO_ERROR = '<?php echo Mage::helper('billmatecommon')->__('Missing Social Security Number / Corporate Registration Number'); ?>';

</script>
