<?php
$gateway = $this->getGatewayPayment();
$compayName = $this->getCompanyName();
$countryCode = $this->getCountryCode();
?>
<script type="text/javascript">
    ShowMessage(
        '<span style="line - height: 1.4em;">' +
        '<?php echo $compayName ?><br/>' +
        '<?php echo $gateway->street ?><br/>' +
        '<?php echo $gateway->postcode ?><br/>' +
        '<?php echo $gateway->city ?><br/>' +
        '<?php echo $countryCode ?><br/>' +
        '<div style="margin - top:1em">' +
        '<input type="button" id="updateAddressYes" onclick="updateAddress()" ' +
        'value="<?php echo $this->__('Yes, make purchase with this address.') ?>" class="billmate_button"/>' +
        '</div>'+
        '<div><a onclick="modalWin . HideModalPopUp();" ' +
        'class="linktag" ><?php echo $this->__('No, I want to specify another person / company or change payment method.') ?></a></div>' +
        '</span>','<?php echo $this->__('Pay with invoice can only be made with a registered adress. Would you like to make the purchase with the following registered address:')?>')
</script>

