<script type="text/javascript">
    // if Firecheckout active
    <?php if(Mage::getStoreConfig('firecheckout/general/enabled')){?>
    // If billmateLoaded == false
    if(!window.billmatepopupLoaded){
        var jq = document.createElement('script');
        jq.type = "text/javascript";
        jq.src = "/skin/frontend/base/default/js/billmatepopup-fc.js";
        document.getElementsByTagName('head')[0].appendChild(jq);
    }
    <?php } else { ?>
        // If billmateLoaded == false
        if(!window.billmatepopupLoaded){
            var jq = document.createElement('script');
            jq.type = "text/javascript";
            jq.src = "/skin/frontend/base/default/js/billmatepopup.js";
            document.getElementsByTagName('head')[0].appendChild(jq);
        }

    <?php } ?>

var billmateindexurl = "<?php echo Mage::getUrl('billmateinvoice/index', array('_secure'=> Mage::app()->getFrontController()->getRequest()->isSecure())) ?>";
var billmatesaveurl  = '<?php echo Mage::getUrl('billmateinvoice/index/updateAddress', array('_secure'=> Mage::app()->getFrontController()->getRequest()->isSecure()));?>';
var skinurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>';
var fireoldurl = null;
var PARTPAYMENT_EID = '<?php echo Mage::getStoreConfig('payment/partpayment/eid'); ?>';
</script>
