<script type="text/javascript">
if(!window.billmatepopupLoaded){
    var jq = document.createElement('script');
    jq.type = "text/javascript";
<?php if(Mage::getStoreConfig('firecheckout/general/enabled')): /* if Firecheckout active */ ?>
    jq.src = "<?php echo $this->getSkinUrl('js/billmatepopup-fc.js'); ?>";
<?php elseif(Mage::getStoreConfig('onestepcheckout/general/active')): /* One step Checkout */ ?>
    jq.src = "<?php echo $this->getSkinUrl('js/billmatepopup-osc.js'); ?>";
<?php elseif(Mage::getStoreConfig('streamcheckout/general/enabled')): /* Stream checkout */?>
    jq.src = "<?php echo $this->getSkinUrl('js/billmatepopup-stream.js'); ?>";
<?php else: /* Standard checkout or not needed special threat */ ?>
    jq.src = "<?php echo $this->getSkinUrl('js/billmatepopup.js'); ?>";
<?php endif; ?>
    document.getElementsByTagName('head')[0].appendChild(jq);
}

var billmateindexurl = "<?php echo Mage::getUrl('billmateinvoice/index', array('_secure'=> Mage::app()->getFrontController()->getRequest()->isSecure())) ?>";
var billmatesaveurl  = '<?php echo Mage::getUrl('billmateinvoice/index/updateAddress', array('_secure'=> Mage::app()->getFrontController()->getRequest()->isSecure()));?>';
var skinurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>';
var fireoldurl = null;
var PARTPAYMENT_EID = '<?php echo Mage::getStoreConfig('payment/billmatepartpayment/eid'); ?>';
var billmatecust_loggedin = '<?php echo Mage::getSingleton('customer/session')->isLoggedIn() ? "true" : "false" ?>';
</script>
