<script type="text/javascript">
var billmateindexurl = "<?php echo Mage::getUrl('billmateinvoice/index', array('_secure'=> Mage::app()->getFrontController()->getRequest()->isSecure())) ?>";
var billmatesaveurl  = '<?php echo Mage::getUrl('billmateinvoice/index/updateAddress', array('_secure'=> Mage::app()->getFrontController()->getRequest()->isSecure()));?>';
var skinurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>';
var fireoldurl = null;
var PARTPAYMENT_EID = '<?php echo Mage::getStoreConfig('payment/partpayment/eid'); ?>';
</script>