<?php $gateway = Mage::getSingleton('billmateinvoice/gateway');

$fieldname = array(	'street][','city','postcode');
$groupname = array('billing','shipping');
$address   = array_combine(
				$fieldname,
				array($gateway->street, $gateway->city, $gateway->postcode)
			);
if(strlen($gateway->getFirstname())>0){
	$fieldname[] = 'firstname';
	$address['firstname'] = $gateway->getFirstname();
}
if(strlen($gateway->getLastname())>0){
	$fieldname[] = 'lastname';
	$address['lastname'] = $gateway->getLastname();
}
if(strlen($gateway->getCompany())>0){
	$fieldname[] = 'company';
	$address['company'] = $gateway->getCompany();
}

if($this->isMatched()):
	echo 'if(typeof streamcheckout != "undefined"){'."\n";
	if(Mage::getStoreConfig('firecheckout/general/enabled') && Mage::getSingleton('customer/session')->isLoggedIn()){
		echo 'billing.newAddress(true)'."\n";

	}
	foreach( $groupname as $group ){
		foreach($fieldname as $row){
			echo 'if($$(\'input[name="'.$group.'['.$row.']"]\').size() > 0 ){ $$(\'input[name="'.$group.'['.$row.']"]\')[0].value="'.$address[$row].'";}',"\n";

		}
		if(Mage::getSingleton('customer/session')->isLoggedIn())
			echo 'if($$(\'input[name="'.$group.'[telephone]"\').size()>0){ $$(\'input[name="'.$group.'[telephone]\')[0].value="'.$gateway->telephone.'";}',"\n";

		echo 'if($$(\'[name="'.$group.'[country_id]"]\').size()>0){ $$(\'[name="'.$group.'[country_id]"]\')[0].value="'.$gateway->country.'";}'."\n";
	}

	echo 'closefunc();modalWin.HideModalPopUp();paymentSave();',"\n";
	echo '}'."\n";

	echo 'if(typeof checkout.form != "undefined"  || typeof checkoutForm != "undefined" || typeof OneStepCheckoutLoginPopup != "undefined"){',"\n";
	if(Mage::getStoreConfig('firecheckout/general/enabled') && Mage::getSingleton('customer/session')->isLoggedIn()){
		echo 'billing.newAddress(true)'."\n";

	}
	foreach( $groupname as $group ){
		foreach($fieldname as $row){
			echo 'if($$(\'input[name="'.$group.'['.$row.']"]\').size() > 0 ){ $$(\'input[name="'.$group.'['.$row.']"]\')[0].value="'.$address[$row].'";}',"\n";
		}
		if(Mage::getSingleton('customer/session')->isLoggedIn())
			echo 'if($$(\'input[name="'.$group.'[telephone]"\').size()>0){ $$(\'input[name="'.$group.'[telephone]\')[0].value="'.$gateway->telephone.'";}',"\n";
		echo 'if($$(\'[name="'.$group.'[country_id]"]\').size()>0){ selectDropDown($$(\'[name="'.$group.'[country_id]"]\')[0],\''.$gateway->country.'\');}',"\n";
	}
	echo 'closefunc();modalWin.HideModalPopUp();',"\n";
	echo '}
paymentSave();';
 ?>

<?php else: ?>
$html='<span style="line-height: 1.4em;"><?php echo ($gateway->company != '') ? $gateway->company : $gateway->firstname.' '.$gateway->lastname; ?><br><?php echo $gateway->street; ?><br><?php echo $gateway->postcode.'<br/>'.$gateway->city.'<br/>'.($gateway->country == 'se' ? '':$gateway->country_name); ?></span><div style="margin-top:1em"><input type="button" id="updateAddressYes" onclick="updateAddress()" value="<?php echo $this->__('Yes, make purchase with this address.')?>" class="billmate_button"/></div><div><a onclick="modalWin.HideModalPopUp();" class="linktag" ><?php echo $this->__('No, I want to specify another person / company or change payment method.')?></a></div>';
ShowMessage($html,'<?php echo $this->__('Pay with invoice can only be made with a registered adress. Would you like to make the purchase with the following registered address:')?>');
<?php endif; ?>
