<?php

if (Mage::getStoreConfig('firecheckout/general/enabled')) ?>
    <script>
        document.observe('dom:loaded',function(){
            var getaddress = '';
            <?php if(Mage::getStoreConfig('billmate/settings/getaddress')){ ?>
                getaddress = '<button class="button" id="billmategetaddress"><span><span><?php echo Mage::helper('billmatecommon')->__('Get Address'); ?></span></span></div>';


            var pno ="<li class=\"wide person_number\"><label for=\"person_number\"><?php echo Mage::helper('billmateinvoice')->__('Person Number'); ?></label>"
            +'<div class="input-box"><input type="text" class="input-text" name="payment[person_number]" id="person_number" title="<?php echo Mage::helper('billmatecommon')->__('Person number'); ?>"/> '+ getaddress +'</div></li>';
            //$('billing-new-address-form').down('ul').innerHTML = pno + $('billing-new-address-form').down('ul').innerHTML;
            $('billing-new-address-form').down('ul').down('li').insert({before: pno});
            <?php } ?>
        });
    </script>
