<?php

if (Mage::getStoreConfig('billmate/settings/firecheckout')) ?>
    <script>
        jQuery(document).ready(function(jQuery){
            jQuery('#billing-new-address-form').children('fieldset').children('ul').prepend("<li class=\"wide\"><label for=\"person_number\"><?php echo Mage::helper('billmateinvoice')->__('Person Number'); ?></label></li>"
            +'<div class="input-box"><input type="text" class="input-text" name="payment[person_number]" id="person_number" title="<?php echo Mage::helper('billmateinvoice')->__('Person number'); ?>"/> </div>');
        });
    </script>
