<script type="text/javascript">
    <?php if(Mage::getStoreConfig('billmate/settings/getaddress')){?>
        document.observe('dom:loaded',function(){
            <?php if(!Mage::getStoreConfig('firecheckout/general/enabled')){ ?>
                var pno = '<li class="fields"><div class="getaddress"><div class="pno" style="float:left;"><label for="pno"><?php echo Mage::helper('billmateinvoice')->__('Person Number'); ?></label><div class="input-box"><input type="text" name="billmate_pno" id="person_number" class="input-text"/></div></div><div style="float:left; padding-top:18px;padding-left:5px;" class="fetch"><div class="input-box"><button class="button" id="billmategetaddress"><span><?php echo Mage::helper('billmatecommon')->__('Get Address'); ?></span></button></div></div></div></li>';
                $('billing-new-address-form').down('ul').innerHTML = pno + $('billing-new-address-form').down('ul').innerHTML;
            <?php } ?>

            $('billmategetaddress').observe('click',function(event){
                event.preventDefault();
                var person_number = $('person_number').value;
                new Ajax.Request('<?php echo Mage::getUrl('billmatecommon/getaddress'); ?>',{
                    method: 'post',
                    parameters: {billmate_pno: person_number},
                    encoding: 'UTF-8',
                    onSuccess: function(transport){
                        var result = transport.responseText.evalJSON();

                        if(result.success){
                            if($('getaddress_failure'))
                                $('getaddress_failure').remove();
                            if(typeof result.data.company != undefined) {
                                $('billing:firstname').value = result.data.firstname;
                                $('billing:lastname').value = result.data.lastname;
                            } else {
                                $('billing:company').value = result.data.company;
                            }
                            $('billing:street1').value = result.data.street;
                            $('billing:city').value = result.data.city;
                            $('billing:postcode').value = result.data.zip;
                            $('billing:country_id').setValue(result.data.country);
                        } else {
                            $('billmategetaddress').insert({after:'<div class="validation-advice" id="getaddress_failure">'+result.message+'</div>'});
                        }
                    }
                })
            })

        });
    <?php } ?>
</script>