<script type="text/javascript">
    <?php if(Mage::getStoreConfig('billmate/settings/getaddress')){?>
        document.observe('dom:loaded',function(){
            <?php if (Mage::getStoreConfig('firecheckout/general/enabled')){ ?>
                    var getaddress = '';
                    getaddress = '<button class="button" id="billmategetaddress"><span><span><?php echo Mage::helper('billmatecommon')->__('Get Address'); ?></span></span></div>';


                    var pno ="<li class=\"wide person_number billmate-getaddress\"><label for=\"person_number\"><?php echo Mage::helper('billmateinvoice')->__('Person Number'); ?></label>"
                        +'<div class="input-box"><input type="text" class="input-text" name="payment[person_number]" id="person_number" title="<?php echo Mage::helper('billmatecommon')->__('Person number'); ?>"/> '+ getaddress +'</div></li>';
                    //$('billing-new-address-form').down('ul').innerHTML = pno + $('billing-new-address-form').down('ul').innerHTML;
                    $('billing-new-address-form').down('ul').down('li').insert({before: pno});


            <?php } elseif (Mage::getStoreConfig('streamcheckout/general/enabled')){ ?>
                    var pno =   '<div class="billmate-getaddress">'+
                        '<div class="field person-number field-type-text">'+
                        '<div class="input-box">'+
                        '<input placeholder="<?php echo Mage::helper('billmatecommon')->__('Person Number');?>" type="text" id="person_number" name="payment[person_number]" title="<?php echo Mage::helper('billmatecommon')->__('Person Number');?>" class="input-text">'+
                        '</div>'+

                        '</div>'+
                        '<button class="button" id="billmategetaddress">'+
                        '<span><span><?php echo  Mage::helper('billmatecommon')->__('Get Address');?></span></span>'+
                        '</button>'+
                        '</div>';

                    $('billing-new-address-form').down('fieldset').down('div').insert({before: pno});
            <?php } else { ?>
                var pno = '<li class="fields">' +
                                '<div class="billmate-getaddress">' +
                                    '<div class="pno">' +
                                        '<label for="pno"><?php echo Mage::helper('billmatecommon')->__('Person Number'); ?></label>' +
                                        '<div class="input-box">' +
                                            '<input type="text" name="billmate_pno" id="person_number" class="input-text"/>' +
                                        '</div>' +
                                    '</div>' +
                                    '<div style="float:left; padding-top:18px;padding-left:5px;" class="fetch">' +
                                            '<div class="input-box">' +
                                                '<button class="button" id="billmategetaddress">' +
                                                    '<span><?php echo Mage::helper('billmatecommon')->__('Get Address'); ?></span>' +
                                                '</button>' +
                                            '</div>' +
                                    '</div>' +
                                '</div>' +
                            '</li>';
                $('billing-new-address-form').down('ul').innerHTML = pno + $('billing-new-address-form').down('ul').innerHTML;
            <?php } ?>

            $('billmategetaddress').observe('click',function(event){
                event.preventDefault();
                var person_number = $('person_number').value;
                new Ajax.Request('<?php echo Mage::getUrl('billmatecommon/getaddress'); ?>',{
                    method: 'post',
                    parameters: {billmate_pno: person_number},
                    encoding: 'UTF-8',
                    onSuccess: function(transport){
                        var result = transport.responseText.evalJSON();

                        if(result.success){
                            if($('getaddress_failure'))
                                $('getaddress_failure').remove();
	                        $('person_number').removeClassName('validation-failed');
                            if(typeof result.data.company != undefined) {
                                $('billing:firstname').value = result.data.firstname;
                                $('billing:lastname').value = result.data.lastname;
                            } else {
                                $('billing:company').value = result.data.company;
                            }
	                        if(result.data.email != ''){

		                        $('billing:email').value = result.data.email;
	                        }
	                        if(result.data.phone != ''){
		                        $('billing:telephone').value = result.data.phone;
	                        }
                            $('billing:street1').value = result.data.street;
                            $('billing:city').value = result.data.city;
                            $('billing:postcode').value = result.data.zip;
                            $('billing:country_id').setValue(result.data.country);
                        } else {
	                        if($('getaddress_failure'))
		                        $('getaddress_failure').remove();
	                        $('person_number').addClassName('validation-failed');
                            $('billmategetaddress').insert({after:'<div class="validation-advice" id="getaddress_failure">'+result.message+'</div>'});
                        }
                    }
                })
            })

        });
    <?php } ?>
</script>