<script type="text/javascript">
    <?php if(Mage::getStoreConfig('billmate/settings/getaddress')){?>
        document.observe('dom:loaded',function(){
            <?php if (Mage::getStoreConfig('firecheckout/general/enabled')){ ?>
                    var getaddress = '';
                    getaddress = '<button class="button" id="billmategetaddress"><span><span><?php echo Mage::helper('billmatecommon')->__('Get Address'); ?></span></span></div>';


                    var pno ="<li class=\"wide person_number billmate-getaddress\"><label for=\"person_number\"><?php echo Mage::helper('billmateinvoice')->__('Social Security Number / Corporate Registration Number'); ?></label>"
                        +'<div class="input-box"><input type="text" class="input-text" value="<?php echo (Mage::getSingleton('checkout/session')->getBillmatePno()) ?Mage::getSingleton('checkout/session')->getBillmatePno() : ''; ?>" name="payment[person_number]" id="person_number" title="<?php echo Mage::helper('billmatecommon')->__('Social Security Number / Corporate Registration Number'); ?>"/> '+ getaddress +'</div></li>';
                    //$('billing-new-address-form').down('ul').innerHTML = pno + $('billing-new-address-form').down('ul').innerHTML;
                    $('billing-new-address-form').down('ul').down('li').insert({before: pno});


            <?php } elseif (Mage::getStoreConfig('streamcheckout/general/enabled')){ ?>
                    var pno =   '<div class="billmate-getaddress">'+
                        '<div class="field person-number field-type-text">'+
                        '<div class="input-box">'+
                        '<input placeholder="<?php echo Mage::helper('billmatecommon')->__('Social Security Number / Corporate Registration Number');?>" value="<?php echo (Mage::getSingleton('checkout/session')->getBillmatePno()) ?Mage::getSingleton('checkout/session')->getBillmatePno() : ''; ?>" type="text" id="person_number" name="payment[person_number]" title="<?php echo Mage::helper('billmatecommon')->__('Social Security Number / Corporate Registration Number');?>" class="input-text">'+
                        '</div>'+

                        '</div>'+
                        '<button class="button" id="billmategetaddress">'+
                        '<span><span><?php echo  Mage::helper('billmatecommon')->__('Get Address');?></span></span>'+
                        '</button>'+
                        '</div>';

                    $('billing-new-address-form').down('fieldset').down('div').insert({before: pno});
            <?php } elseif(Mage::getStoreConfig('onestepcheckout/general/active')){ ?>
                        var getaddress = '';
                        getaddress = '<button class="button" id="billmategetaddress"><span><span><?php echo Mage::helper('billmatecommon')->__('Get Address'); ?></span></span></div>';


                        var pno ="<li class=\"wide person_number billmate-getaddress\"><label for=\"person_number\"><?php echo Mage::helper('billmateinvoice')->__('Social Security Number / Corporate Registration Number'); ?></label>"
                            +'<input type="text" class="input-text" style="width:62%!important" value="<?php echo (Mage::getSingleton('checkout/session')->getBillmatePno()) ?Mage::getSingleton('checkout/session')->getBillmatePno() : ''; ?>" name="payment[person_number]" id="person_number" title="<?php echo Mage::helper('billmatecommon')->__('Social Security Number / Corporate Registration Number'); ?>"/> '+ getaddress +'</li>';
                        //$('billing-new-address-form').down('ul').innerHTML = pno + $('billing-new-address-form').down('ul').innerHTML;
                        $('billing-new-address-form').down('ul').down('li').insert({before: pno});
            <?php }else { ?>
                var pno = '<li class="fields">' +
                                '<div class="billmate-getaddress">' +
                                    '<div class="pno">' +
                                        '<label for="pno"><?php echo Mage::helper('billmatecommon')->__('Social Security Number / Corporate Registration Number'); ?></label>' +
                                        '<div class="input-box">' +
                                            '<input type="text" name="billmate_pno" id="person_number" class="input-text" value="<?php echo (Mage::getSingleton('checkout/session')->getBillmatePno()) ?Mage::getSingleton('checkout/session')->getBillmatePno() : ''; ?>"/>' +
                                        '</div>' +
                                    '</div>' +
                                    '<div style="float:left; padding-top:18px;padding-left:5px;" class="fetch">' +
                                            '<div class="input-box">' +
                                                '<button class="button" id="billmategetaddress">' +
                                                    '<span><?php echo Mage::helper('billmatecommon')->__('Get Address'); ?></span>' +
                                                '</button>' +
                                            '</div>' +
                                    '</div>' +
                                '</div>' +
                            '</li><div style="clear:both;"></div>';
                $('billing-new-address-form').down('ul').innerHTML = pno + $('billing-new-address-form').down('ul').innerHTML;
            <?php } ?>

            $('billmategetaddress').observe('click',function(event){
                event.preventDefault();
                var person_number = $('person_number').value;
                new Ajax.Request('<?php echo Mage::getUrl('billmatecommon/getaddress',array('_secure' => true)); ?>',{
                    method: 'post',
                    parameters: {billmate_pno: person_number},
                    encoding: 'UTF-8',
                    onSuccess: function(transport){
                        var result = transport.responseText.evalJSON();

                        if(result.success){
                            if($('getaddress_failure'))
                                $('getaddress_failure').remove();
	                        $('person_number').removeClassName('validation-failed');

                            if(typeof result.data.company != 'undefined') {
                                $('billing:company').setValue(result.data.company);
                            } else {
                                $('billing:firstname').setValue(result.data.firstname);
                                $('billing:lastname').setValue(result.data.lastname);
                            }

	                        if(result.data.email != ''){

		                        $('billing:email').setValue(result.data.email);
                                <?php if(Mage::getStoreConfig('onestepcheckout/general/active')){ ?>
                                    $('billing:email').triggerEvent('blur');
                                <?php } ?>
	                        }
	                        if(result.data.phone != ''){
		                        $('billing:telephone').setValue(result.data.phone);
	                        }
                            $('billing:street1').setValue(result.data.street);
                            $('billing:city').setValue(result.data.city);
                            $('billing:postcode').setValue(result.data.zip);
                            $('billing:country_id').setValue(result.data.country);
                            $('billing:country_id').triggerEvent('change');

                        } else {
	                        if($('getaddress_failure'))
		                        $('getaddress_failure').remove();
	                        $('person_number').addClassName('validation-failed');
                            $('billmategetaddress').insert({after:'<div class="validation-advice" id="getaddress_failure">'+result.message+'</div>'});
                        }
                    }
                })
            })

        });
    <?php } ?>
</script>