<?php $_code=$this->getMethodCode();
$customerData['email'] = '';
if($customer = Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customerData = Mage::getModel('customer/customer')->load(Mage::getSingleton('customer/session')->getId())->getData();
}else{
$customerData['email'] = Mage::getSingleton('checkout/session')
	->getQuote()
	->getBillingAddress()
	->email;
}

 ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>/billmate/images/bm_faktura_l.png" />
    </li>
    <li>
        <label for="<?php echo $_code ?>_pno" class="required"><em>*</em><?php echo $this->__('Personal Number') ?></label>
        <div class="input-box">
            <input onchange="checkAddress(this)" type="text" title="<?php echo $this->__('Personal Number') ?>" class="input-text required-entry" id="<?php echo $_code ?>_pno" name="payment[<?php echo $_code ?>_pno]" />
        </div>
    </li>
    <li>
		<input type="checkbox" checked="checked" id="<?php echo $_code ?>_phone" name="payment[<?php echo $_code;?>_phone]" title="<?php echo $this->__('Phone Number') ?>" class="required-entry" value="on" style="float:left;margin:3px;" />
        <label for="<?php echo $_code ?>_phone" class="required" style="font-weight:normal"><em>*</em><?php echo $this->__('My email <b>%1$s</b> is accurate and can be used for billing', $customerData['email'] ) ?></label>
    </li>
    <?php echo $this->getChildHtml() ?>
</ul>
<script type="text/javascript">
var billmateindexurl = "<?php echo Mage::getUrl('billmateinvoice/index') ?>";
var billmatesaveurl  = '<?php echo Mage::getUrl('billmateinvoice/index/updateAddress');?>';
var skinurl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) ?>';
</script>
