<?php
/**
 * Created by Boxedsolutions.
 * Author: Jesper Johansson <jesper@boxedlogistics.se>
 * Project: NMC_new
 * Date: 2016-01-18
 * Time: 18:07
 */
$lang = explode('_',Mage::app()->getLocale()->getLocaleCode());
?>

<?php if($title = $this->getPayFrom()): ?>
	<div class="billmate-wrap">
		<label class="part-payment-label"><?php echo $this->__('Pay from'); ?><?php echo $title; ?></label>
		<img class="payment-thumb" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>/billmate/images/<?php echo $lang[0] == 'sv' ? $lang[0] : 'en'; ?>/partpayment.png">
    <div class="billmate-partpay"></div>
    </div>
<?php endif; ?>