<script type="text/javascript">
    function update(){


        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>',{
            method: 'get',
            onSuccess: function(transport){
                if(transport.responseText){
                    var response = transport.responseText.evalJSON();
                    if(response.success)
                        alert('Updated paymentplans');
                    else
                        alert('Couldnt update paymentplans');
                }
            }
        })
    }
</script>

<?php echo $this->getButtonHtml(); ?>