<script type="text/javascript">
    function verify(){

        var eid = $('billmate_credentials_eid').value;
        var secret = $('billmate_credentials_secret').value;
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>',{
            method: 'post',
            parameters: {
                eid: eid,
                secret: secret
            },
            onSuccess: function(transport){
                if(transport.responseText){
                    var response = transport.responseText.evalJSON();
                    if(response.success){
                        if($('error'))
                            $('error').remove();
                        $('billmatecommon_verify').insert({after:'<h3 id="verified" style="color:green;"><?php echo Mage::helper('billmatecommon')->__('Verified'); ?></h3>'})

                    } else {
                        if($('verified'))
                            $('verified').remove();
                        $('billmatecommon_verify').insert({after:'<h3 id="error" style="color:red;"><?php echo Mage::helper('billmatecommon')->__('Invalid credentials'); ?></h3>'})

                    }

                }
            }
        })
    }
</script>

<?php echo $this->getButtonHtml(); ?>